platform :ios, '9.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/angryDuck2/CocoaSpecs'

target "Popcorn Time" do
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'AlamofireNetworkActivityIndicator'
    pod 'KMPlaceholderTextView'
    pod 'SwiftyJSON'
    pod 'FloatRatingView', git: 'https://github.com/strekfus/FloatRatingView.git'
    pod 'AlamofireXMLRPC', git: 'https://github.com/PopcornTimeTV/AlamofireXMLRPC.git'
    pod 'Reachability'
    pod 'XCDYouTubeKit'
    pod 'JGProgressHUD'
    pod 'google-cast-sdk'
    pod 'GZIP'
    pod 'OBSlider'
    pod 'ColorArt'
    pod '1PasswordExtension'
    pod 'PopcornTorrent', git: 'https://github.com/PopcornTimeTV/PopcornTorrent.git'
    pod 'MobileVLCKit-unstable', '3.0.0a10'
    pod 'SwiftyTimer'
    pod 'SRT2VTT'
    pod 'R.swift', '~> 2.5'
    pod 'PullToRefreshSwift', '~> 2.0'
    pod 'SwiftyUserDefaults', '~> 2.2'
end
